### ISSUE TITLE
From the next BookStack feature release, `APP_KEY` will need to be set and stable

### ISSUE THREAD

**Issue by ssddanbrown** [linuxserver/docker-bookstack#105]
:wave: Let me know if your forum or discord is more appropriate for this, just didn't want it to be missed and was therefore not sure on most appropriate option to communicate this across. 

Just wanted to give a heads-up. As of the next feature release the `APP_KEY` .env option will need to validly exist and be consistent across restarts. Ideally people will need to know to retain that value. Not sure on the depth it'll affect this project but warning early just in case. This is due to the use of encryption within the new multi-factor-authentication system.

At a guess, the next feature release will arrive in about 1-2 weeks. Happy to provide more info or answer any questions if needed.

**Comment by TheSpad** [comment]
We have for some time generated an APP_KEY value [on initial startup](https://github.com/linuxserver/docker-bookstack/blob/3aec0b9e4974eed807f2f363c250b8e62abadf01/root/etc/cont-init.d/50-config#L35-L46) and then leave it as-is unless the user decides to change it.

Should cover this off but let us know if you think there's any issue with what we're doing.

**Comment by homerr** [comment]
Appreciate the heads up on this one! It *should* be ok the way it is, but like Spad said if you see anything that could bork that let us know.

**Comment by ssddanbrown** [comment]
@TheSpad @homerr Ah, That's perfect! Didn't realise you put that out to it's own text file. Looking back on some of my own linuxserver setups I can see that file in there. Thanks both. Will therefore close this off.
