### ISSUE TITLE
failed to upgrade to v21.08.2

### ISSUE THREAD

**Issue by iml885203** [linuxserver/docker-bookstack#107]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Steps to Reproduce

1. edit `docker-compose.yaml` change image from `v21.08.1` to `v21.08.2`
2. run `docker-compose up -d`
3. show nginx page: not found.

## Docker logs

```log
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
New container detected. Setting up app folder and fixing permissions.
ln: failed to create symbolic link '/var/www/html/storage/uploads/files': No such file or directory
ln: failed to create symbolic link '/var/www/html/storage/uploads/images': No such file or directory
ln: failed to create symbolic link '/var/www/html/storage/logs/laravel.log': No such file or directory
App Key found - setting variable for seds
Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 97: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 97: warning: command substitution: ignored null byte in input
Could not open input file: /var/www/html/artisan
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by cb3inco** [comment]
@iml885203 I've run into this problem too. By chance, are you making custom template changes? That was my problem and I had to remove that to get things working.

**Comment by iml885203** [comment]
I have mounted the icon to the container before.
```
volumes:
  - ~/bookstack/config:/config
  - ./favicon.ico:/var/www/html/public/favicon.ico
```
When I comment it, it worked!

**Comment by cb3inco** [comment]
Yes, I've opened a feature request to be able to customize things. I've asked the developer if security changes in v21.08.2 would have broken this. Might be a specific Linuxserver container issue.

**Comment by ssddanbrown** [comment]
Can't think of anything on the BookStack side that would cause such issues.

Looking at a comparison of the latest v21.08.1 and v21.08.2 states of this repo:
https://github.com/linuxserver/docker-bookstack/compare/v21.08.1-ls156...v21.08.2-ls158

There seems to be a `overlay-fs bug workaround` added that moves files in and out of `/var/www` via a temp directory. Possibly this causes issues and conflicts when a `/var/www/*` folder is manually mounted?

**Comment by drizuid** [comment]
OP did not fully fill out the issue template which prevents recreation of the issue within the team. As a note, based on the conversation, our containers expect our readme to be followed. If an advanced user is doing unexpected things, they are expected to resolve them OR submit a fully tested PR and justification for the changes to be merged.
