### ISSUE TITLE
Database values are not updated

### ISSUE THREAD

**Issue by calvinbui** [linuxserver/docker-bookstack#109]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Changing the `DB_HOST`, `DB_DATABASE`, `DB_USERNAME` or `DB_PASSWORD` values should update the `/config/www/.env` file values.

## Current Behavior

The `sed` command only replaces the default values. 

The script also exits successfully (0) afterwards when there is an error.

See file: See file: https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L65-L68

## Steps to Reproduce

1. Change any of the `DB_HOST`, `DB_DATABASE`, `DB_USERNAME` or `DB_PASSWORD` environment values
2. `/config/www/.env` is not updated to the correct value
3. The application fails to connect

## Docker logs

```
/var/run/s6/etc/cont-init.d/50-config: line 97: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 97: warning: command substitution: ignored null byte in input

   Illuminate\Database\QueryException  : SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'1.2.3.4' (using password: YES) (SQL: select * from information_schema.tables where table_schema = bookstack and table_name = migrations and table_type = 'BASE TABLE')

  at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[HY000] [1045] Access denied for user 'bookstackuser'@'192.168.4.162' (using password: YES)")
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18

  2   Doctrine\DBAL\Driver\PDO\Exception::new()
      /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43

  Please use the argument -v to see more details.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
```

**Comment by crpb** [comment]
I just switched to mysql/mysql-server because of this.

My steps to reproduce
```
# shutdown docker instance of bookstack
docker sytem prune --all
rm -Rf bookstack/ bookstack_db/
docker-compose up bookstack_db
# another terminal
cp dump.sql bookstack_db/config/
docker exec -it bookstack_db /bin/bash
mysql -u root -p bookstackapp < dump.sql
# outside again
tar xfv backup-of-bookstack-data.tar.gz  (bookstack/config/BOOKSTACK_APP_KEY.txt, bookstack/config/www/.env, bookstack/config/www/uploads/*)
docker-compose up bookstack
# looks great , everything works..
# another terminal
docker-compose down
# wait a bit..
docker-compose up -d
# and now the Database broke again and again and again...
```

I did this thrice just to be safe.. same behaviour.
After that i switched to mysql/mysql-server ..  just because i wanted it going again on this lovely sunday evening.

The Shutdown seems just not safe of the mariadb-instance.. i  think i got a return 134 once if thats possbile ..


I had a similiar problem a couple months ago with the one of the tables.. after hours i found that i could just delete the coresponding row/column in the databse..  ''entitites'' i think. after recovering _this_ and _that_ ....
[bookstack-docker-compose.txt](https://github.com/linuxserver/docker-bookstack/files/7493132/bookstack-docker-compose.txt)
[docker-log.txt](https://github.com/linuxserver/docker-bookstack/files/7493153/docker-log.txt)

**Comment by matthijsbro** [comment]
I just may have found the cause. If you copied docker-compose from the readme.md here it said DB_PASS where it should be DB_PASSWORD

**Comment by jonasanker** [comment]
@matthijsbro From what I can see the `DB_PASS` variable is converted and set to the Bookstack expected `DB_PASSWORD` when the container is created the first time. So that would not be the cause. 

See https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L61
```bash
if [ "${DB_USER}" ];
	then
	echo "Running config - db_user set"
	ESCAPED_PASSWORD=$(sed -e 's/[$\/&]/\\&/g' <<< $DB_PASS)
	sed -i "s/DB_HOST=localhost/DB_HOST=${DB_HOST}/g" /config/www/.env
	sed -i "s/DB_DATABASE=database_database/DB_DATABASE=${DB_DATABASE}/g" /config/www/.env
	sed -i "s/DB_USERNAME=database_username/DB_USERNAME=${DB_USER}/g" /config/www/.env
	sed -i "s/DB_PASSWORD=database_user_password/DB_PASSWORD=${ESCAPED_PASSWORD}/g" /config/www/.env
fi
```

**Comment by matthijsbro** [comment]
I know very little about this. I can only conclude that the change made it work for me.
