### ISSUE TITLE
Allow APP_KEY to be declared as an Env Var

### ISSUE THREAD

**Issue by stavros-k** [linuxserver/docker-bookstack#118]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior
I'd like to set APP_KEY via an env var

## Current Behavior
It's auto generated or sourced from the .env file

**Comment by drizuid** [comment]
OP didn't provide any relevant info on this feature request in a reasonable amount of time.
