### ISSUE TITLE
LDAP PHP extension not installed

### ISSUE THREAD

**Issue by Swish24** [linuxserver/docker-bookstack#12]
I have enabled advanced mode with the latest container, configured the LDAP authentication settings and enabled LDAP auth. When attempting to logon to bookstack after restarting the container, it displays that the LDAP PHP extension is not installed.

Host OS - Ubuntu 16.04
Output log, no errors appear in the log
![unknown](https://user-images.githubusercontent.com/27150190/47621887-2fc55080-dabb-11e8-9e4f-71b4dd009475.png)

**Comment by homerr** [comment]
Will get this added today

**Comment by homerr** [comment]
Sorry for delay. PR open to fix #14

**Comment by homerr** [comment]
Merged
