### ISSUE TITLE
Reference to heimdall in BookStack file.

### ISSUE THREAD

**Issue by greenerk** [linuxserver/docker-bookstack#120]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Not find references to other projects within this one.

## Current Behavior
docker-bookstack/root/defaults/default has a line referencing docker-heimdall.

## Steps to Reproduce
1. Go to docker-bookstack/root/defaults/default
2. Read first line.

Not a bug as such - but may highlight some needed housekeeping within other projects.

**Comment by drizuid** [comment]
This was addresses in the standard base PR, thanks for pointing it out to us!
