### ISSUE TITLE
Bookstack proxied through Cloudflare has unclickable buttons

### ISSUE THREAD

**Issue by Lex1020** [linuxserver/docker-bookstack#121]
I just set up a bookstack wiki and noticed that when it is proxied through Cloudflare it seems that some of the stuff doesn't work. 

An example of this is the profile tab in the top right.  When I access the page without proxing through Cloudflare it is clickable but when proxied through Cloudflare clicking does nothing. 

The same goes with things like making a new page. If I proxy then all I can edit is the title of the page, if I'm not proxying then I edit the body of the page. 

Finally, other things like anything that has a collapsible menu does not work when proxied through Cloudflare.

**Comment by j0nnymoe** [comment]
You've not filled out the issue template but unless you have this issue when the site isn't proxied through cloudflare, I would say it's an issue with your cloudflare settings and not the container itself.

**Comment by ssddanbrown** [comment]
I think this could probably be closed as it's not something specific to linuxserver, this occurs in non-docker scenarios also. In particular it's caused Cloudflare's rocket loader. 

@Lex1020 You should be able to disable the rocker loader in cloudflare to make things work again: https://support.cloudflare.com/hc/en-us/articles/200168056-Understanding-Rocket-Loader
