### ISSUE TITLE
After updating my docker container to the latest version I keep getting these error messages in the logs

### ISSUE THREAD

**Issue by BobWs** [linuxserver/docker-bookstack#124]
After updating my docker container to the latest version I keep getting these error messages in the logs
```
/var/run/s6/etc/cont-init.d/50-config: line 98: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 98: warning: command substitution: ignored null byte in input
```
Any thought on how to solve this?

TIA

**Comment by thespad** [comment]
They're not errors per se, the init script is waiting for the database to be available. It's a bug (it shouldn't be outputting an error) but it's harmless.
