### ISSUE TITLE
MFA not working due to Time sync not being included in template

### ISSUE THREAD

**Issue by cj2tech** [linuxserver/docker-bookstack#143]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

When you first set up the docker template it will work fine except the time will be off due to the application container not having correct time. Some things are broken because of this like MFA.
------------------------------

## Expected Behavior

MFA to function normally and time be synced in the container

## Current Behavior

Due to the current templet there is no way for the application to get the correct time

## Steps to Reproduce

1. Set up docker-compose
2. login
3. goto edit profile
4. tried to enable and setup TOTP MFA

## Environment
**OS:** Linux
**CPU architecture:** x86_64
**How docker service was installed:**
used docker compose template from [https://hub.docker.com/r/linuxserver/bookstack](https://hub.docker.com/r/linuxserver/bookstack). Setup as a stack in Portainer

## Command used to create docker container (run/create/compose/screenshot)
 Compse

## Docker logs

n/a -

**Comment by cj2tech** [comment]
since the container wasn't configured correctly I was able to add `-v /etc/localtime:/etc/localtime:ro` so the container used my systems time rather than relying on the container. It looks like you guys have a `-e TZ` set for the database but not the main app. IDK if that would also resolve the issue or not. But really there shouldn't be any issue adding the time based off the system either.

This issue is resolved I just wanted to note it down and make other people aware and provide them a fix

**Comment by drizuid** [comment]
thanks for opening this issue, it looks like we somehow missed putting our normal TZ recommendation in the compose sample. We will get the readme addressed asap.

as a side note, for future reference, 
Command used to create docker container (run/create/compose/screenshot)
the answer to this for you is portainer, not compose.   when we say compose, we mean docker compose, when portainer says compose, they mean portainershitshow.
