### ISSUE TITLE
How to change favicon

### ISSUE THREAD

**Issue by jeffshead** [linuxserver/docker-bookstack#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Uses original favicon.

## What is the correct way to use a custom favicon?
This does not work:
```
volumes:
      - /path/to/data:/config
      - /path/to/favicon.ico:/var/www/html/public/favicon.ico
```

### Expected Behavior

Use my custom favicon.

### Steps To Reproduce

Install BookStack and access webpage.

### Environment

```markdown
- OS:AlmaLinux 8.7
- How docker service was installed: DNF
```

### CPU architecture

x86-64

### Docker creation

```bash
Using Portainer.
```

### Container logs

```bash
N/A
```

**Comment by ssddanbrown** [comment]
I believe this can now be closed since OP found a solution, and since we'll have built-in favicon change support built-in as of next release. [Relevant BookStack thread](https://github.com/BookStackApp/BookStack/issues/3929).
