### ISSUE TITLE
[BUG] Update to v23.02.1 prevents emails from sending

### ISSUE THREAD

**Issue by Virtike** [linuxserver/docker-bookstack#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Emails sent via authenticated SMTP on 23.02.1 report as sent without any errors reported/logged, but never actually send.

Something in the update from v23.01.1 to v23.02.1 has broken emails being able to send for me. The success message appears when sending an email via user signup or the email test, and there are no errors reported on sending an email - however the email never sends. 

Cannot find any record of errors in any of the logs (be that laravel, php or nginx - which seems odd), SMTP details are correct, & emails are sent/delivered as expected on v23.01.1 and previous.

### Expected Behavior

Emails sent via authenticated SMTP as expected

### Steps To Reproduce

1. Update to v23.02.1
2. Send test email
3. Email never sent/delivered
4. Change to linuxserver/bookstack:23.01.1 - same .env & config
5. Send test email
6. Emails sent/delivered as expected

### Environment

```markdown
- OS: Unraid Version: 6.9.2
- Docker Version: 20.10.5
```

### CPU architecture

x86-64

### Docker creation

```bash
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='bookstack' --net='bridge' -e TZ="####" -e HOST_OS="Unraid" -e 'APP_URL'='https://bookstack.####.au' -e 'DB_HOST'='####' -e 'DB_USER'='bookstackuser' -e 'DB_PASS'='####' -e 'DB_DATABASE'='bookstackapp' -e 'DB_PORT'='6876' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -p '6875:80/tcp' -v '/mnt/user/appdata/bookstack':'/config':'rw' 'lscr.io/linuxserver/bookstack'
3a61e1dbe0a44899f1d0cbe426ad490d8ff1219f5c7e675608001c10c0dbaeb1

note: #### = redacted
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

using keys found in /config/keys
App Key found - setting variable for seds
Running config - DB_HOST set
Waiting for DB to be available
Nothing to migrate.
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-05 │ 2022-08-20 │ /config/nginx/ssl.conf                                                 │
│            │ 2022-08-16 │ /config/nginx/nginx.conf                                               │
│ 2018-03-06 │ 2022-10-04 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by ssddanbrown** [comment]
Just gave this a test, using the `lscr.io/linuxserver/bookstack:latest (id=d376aeab7a2d)` image, with SMTP details set-up to use mailtrap. All seems to work fine.
Tested with and without TLS encryption options. 

You sure things aren't being silently spam-filtered?

**Comment by ReVoLt112** [comment]
Mails are working for me with authenticated SMTP [BookStack v23.02.1 ]. I could not reproduce this issue

**Comment by Virtike** [comment]
Okay thank you for confirming. Looking at the firewall logs I can see a successful connection out to the SMTP provider (Bluehost) via port 465, so perhaps it is actually something on their end. What I don't quite understand is why reverting to v23.01.1 would resolve the problem (repeatable), when there don't appear to be any changes to the SMTP implementation & the config between versions doesn't change.

Will see if I can test with a different SMTP server.

**Comment by Virtike** [comment]
Can confirm it seems to be something on SMTP provider Bluehost's end. Changed over to sending va SendGrid and emails are delivered as expected. Will close the issue.
