### ISSUE TITLE
Change README to add the different mappings for images

### ISSUE THREAD

**Issue by H-Toine** [linuxserver/docker-bookstack#167]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add the different mapping for the image locations to the documentation.

### Reason for change

As experienced from [an issue on the official bookstack repo](https://github.com/BookStackApp/BookStack/issues/4161) , the mapping is different from the docker image to the official bookstack repo.

This conflicts with the official bookstack documentation. When changing your image storage_type from `local`  (publicly available) to `local_secure` (only logged in users), the [documentation](https://www.bookstackapp.com/docs/admin/upload-config/#migrating-to-secure-images) tells you to move the images to a different location. The different locations of the folders in the docker image makes this documentation invalid.

As such, I'd propose to add the mapping to the README (or wherever you see fit).

### Proposed code change

```md
  #### Different paths for secure images
  This docker image exposes the internal BookStack folders under different paths. Below is the current mapping:
  
  Location within mounted /config folder => Normal BookStack filesystem location
  - www/files => storage/uploads/files
  - www/images => storage/uploads/images
  - www/themes => themes
  - uploads => public/uploads
```

**Comment by ssddanbrown** [comment]
I've opened a PR for this in #168. In my PR I've made the wording a bit more generic than requested/suggested above since these paths can be useful to know in a range of scenarios, not just those in a "storage_type"/"secure-images" context.

**Comment by ssddanbrown** [comment]
Thank you very much @thespad for the review and merge!
