### ISSUE TITLE
DB password

### ISSUE THREAD

**Issue by p6002** [linuxserver/docker-bookstack#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Docker compose file works only with `<yourdbpass>` instead of normal password here:
- `DB_PASS=<yourdbpass>`

Can you please provide random password string as template for me? 

### Steps To Reproduce

Trying to use bookstack via docker compose.

### Environment

```markdown
- OS: Ubuntu Server 22
- How docker service was installed: normal way
```

### CPU architecture

arm64

### Docker creation

```bash
docker compose up
```

### Container logs

```bash
---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://192.168.1.100:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=<yourdbpass>
      - DB_DATABASE=bookstackapp
    volumes:
      - ./bookstack_app_data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
      
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=<yourdbpass>
      - TZ=Europe/Amsterdam
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=<yourdbpass>
    volumes:
      - ./bookstack_db_data:/config
    restart: unless-stopped
```

**Comment by Gamechiefx** [comment]
Thank you for this..... Fresh install of Bookstack docker and it would appear that <yourdbpass> is the right password when it was set to a defined password before docker-compose run. Something is messed up here big time with the compose functions to set MySQL passwords on first run.
