### ISSUE TITLE
[FEAT] Add ability to configure queue worker process to support async action handling

### ISSUE THREAD

**Issue by cdrfun** [linuxserver/docker-bookstack#186]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Running queue worker processes are required to support async action handling in Bookstack. Currently, there as no way to configure and run the queue worker process using this docker image. Bookstack documentation can be found here: https://www.bookstackapp.com/docs/admin/email-webhooks/#async-action-handling

### Reason for change

As stated in the Bookstack documentation:
_Actions like sending email or triggering webhooks are performed synchronously by default which can slow down page loading when those actions are triggered. These actions can instead be processed asynchronously so they’re handled in the background to prevent slowing down the request. This requires a config change and a queue worker process to handle these background jobs:_

**Comment by thespad** [comment]
Can you test `lspipepr/bookstack:v23.08.1-pkg-abf62b2e-dev-7245559a0085b0d51594e140e1ec1bcae76aff08-pr-187` and see if it works for you? Just set `QUEUE_CONNECTION=database` as an environment variable and that should enable the queue.

**Comment by cdrfun** [comment]
Wow, super fast: It seems to work for me `ps aux` shows `/usr/bin/php /app/www/artisan queue:work --sleep=3 --tries=1 --max-time=3600` after starting the container.

**Comment by thespad** [comment]
Thanks for checking. Once the PR has been reviewed within the team I'll get it merged.
