### ISSUE TITLE
Nginx can not support IPV6？

### ISSUE THREAD

**Issue by jyxgood** [linuxserver/docker-bookstack#199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to deploy on my web container, there is some error message with the proxy. It seems to be nginx can not support Ipv6

![image](https://github.com/linuxserver/docker-bookstack/assets/7713037/a7cce8b9-6208-46b3-9df1-d4af08ddfc86)

### Steps To Reproduce

railway.app service

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
railway.app service
```

### Container logs

```bash
nginx: [emerg] invalid port in resolver "fd12::10" in /config/nginx/resolver.conf:3

nginx: [emerg] invalid port in resolver "fd12::10" in /config/nginx/resolver.conf:3

nginx: [emerg] invalid port in resolver "fd12::10" in /config/nginx/resolver.conf:3
```

**Comment by jyxgood** [comment]
> That's an issue with our baseimage. It reads the resolv.conf and interprets it for Nginx. It's supposed to ignore ipv6 entries but it seems to have failed in this case.
> 
> This is the code responsible: https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/master/root/etc/s6-overlay/s6-rc.d/init-nginx/run#L38-L53
> 
> Please post the contents of your `/etc/resolv.conf` from inside the container so we can try and mitigate.

the support of railway.app told me they don't have ssh or ftp functional to enter the container. I think the problem may be  they use only IPV6 nameserver.

**Comment by aptalca** [comment]
??
`docker exec -it bookstack bash` gets you into the container terminal
