### ISSUE TITLE
[FEAT] Add Version Tags to docker images

### ISSUE THREAD

**Issue by kale1d0code** [linuxserver/docker-bookstack#204]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

To add version tags to docker images so I can pin software version

### Reason for change

To be able to continue receiving OS updates for the container but keep current app version

### Proposed code change

change the release script so that it adds version tags to docker images as they are being published

**Comment by Roxedus** [comment]
The requested changes are not feasible.

**Comment by ssddanbrown** [comment]
Looking at the tags applied, I thought this was already done tbh. for example: `lscr.io/linuxserver/bookstack:version-v23.12.1`.

**Comment by kale1d0code** [comment]
I found out a way to view tags that could be on the linuxserver image registry.
Looking into the Dockerfile, it looks at https://api.github.com/repos/bookstackapp/bookstack/releases
navigating to this page and reading the JSON it is possible to find the version numbers for the bookstack images.

Using the latest version I was able to find a manifest for: lscr.io/linuxserver/bookstack:23.12.1

I've had difficulty finding the schema linuxserver uses for version tags as its not possible to view available tags on lscr.io and they are not documented anywhere

**Comment by ssddanbrown** [comment]
@kale1d0code I looked to the container package for this repo; provides an easier to read view:
https://github.com/linuxserver/docker-bookstack/pkgs/container/bookstack

**Comment by thespad** [comment]
https://www.linuxserver.io/blog/docker-tags-so-many-tags-so-little-time

**Comment by aptalca** [comment]
Also, Docker hub allows for filtering and searching through tags, which is quite a bit nicer than ghcr.

https://hub.docker.com/r/linuxserver/bookstack/tags

However that doesn't change the fact that the following request is not feasible (as rox mentioned)
`To be able to continue receiving OS updates for the container but keep current app version`

You can pin to an older version/tag, but that older version/tag will not receive os package updates. Only the latest/current version/tag will.
