### ISSUE TITLE
[BUG] uploaded images can not be found after move to container

### ISSUE THREAD

**Issue by andreasbrunsdgn** [linuxserver/docker-bookstack#210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I migrate a bookstack server from VM installation to the container version, then the uploaded images can not be found.

workaround / possible fix: adjust doku on https://github.com/linuxserver/docker-bookstack#bookstack-file--directory-paths
IMHO "/config/www/images/ => storage/uploads/images/" is wrong. It should be
/config/www/upload/images/ => storage/uploads/images/

### Expected Behavior

Images are displayed and found after migration.

### Steps To Reproduce

setup an container bookstack and migrate data following readme

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d --remove-orphans
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1001
User GID:    1001
───────────────────────────────────────

using keys found in /config/keys
App Key found - setting variable for seds
Running config - DB_HOST set
Waiting for DB to be available

   INFO  Nothing to migrate.

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by ssddanbrown** [comment]
> IMHO "/config/www/images/ => storage/uploads/images/" is wrong. It should be
/config/www/upload/images/ => storage/uploads/images/

I just doubled checked this and what's already written seems correct to me.
The `/config/www/upload/images/` path maps to `public/uploads/images` which is aligned with the documentation.
Both are possible locations for images to be stored, and which one you'd be moving your images to depends on the storage options set for BookStack (or at least where you are moving images from).
