### ISSUE TITLE
[FEAT] SSL certificate change

### ISSUE THREAD

**Issue by kaju666** [linuxserver/docker-bookstack#220]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Possibility to add own certificate file (.pfx)
Or instruction how to do it :)

### Reason for change

Increasing security.

**Comment by j0nnymoe** [comment]
The recommendation is to put the container behind a reverse proxy.
Though you are free to configure the container as you wish as it's just nginx hosting bookstack in the container.
