### ISSUE TITLE
[FEAT] Merge page 

### ISSUE THREAD

**Issue by joel72265** [linuxserver/docker-bookstack#223]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Thank you for a wonderful software

When a user with the Create/Edit role updates a page, his/her page update is not published until it is approved by Editor/author

### Reason for change

I think this will be helpful when updating pages, especially for teams

### Proposed code change

NA

**Comment by j0nnymoe** [comment]
This needs to be requested to bookstack, not us.

**Comment by joel72265** [comment]
thank you, I chimed in on a similar post on bookstack
