### ISSUE TITLE
[BUG] Open Relay Mail sending from the same network

### ISSUE THREAD

**Issue by fnrcum** [linuxserver/docker-bookstack#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When setting the MAIL_PORT to 25 and setting the encryption to null and verify to false, the app still cannot send emails because it still forces starttls.

In the cases where the application is internal and uses your mailing server as an open relay using the local network ips, is there a way to force it not to use starttls without forcing the mail server to stop advertising it?

### Expected Behavior

  -e MAIL_DRIVER=smtp \
  -e MAIL_HOST=<IP> \
  -e MAIL_PORT=25 \
  -e MAIL_ENCRYPTION=tls \
  -e MAIL_VERIFY_SSL=false \
  
  We should be able to send an email if the server is configured as an open relay with whitelisted sources inside the local network.

### Steps To Reproduce

Set the mail configs to the following values

  -e MAIL_DRIVER=smtp \
  -e MAIL_HOST=<IP> \
  -e MAIL_PORT=25 \
  -e MAIL_ENCRYPTION=tls \
  -e MAIL_VERIFY_SSL=false \
  
  
  Setup an open relay local mailing server that is correctly configured to send/receive emails
  Try sending a test mail from the app

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
not relevant
```

### Container logs

```bash
not relevant
```

**Comment by j0nnymoe** [comment]
Haven't dived into the code but I'm pretty sure those aren't valid ENV's so you'd need to manually edit the `.env` file within the `/config` mount.

**Comment by thespad** [comment]
We should pass through anything set so if the app supports it then it should work, but I can't speak to the validity of any particular combination of options, you'd need to check the application documentation.

**Comment by fnrcum** [comment]
The values are directly from the docs and they work with other values that don't rely on an open relay. The only problem is that we can't use an local network open relay on port 25 without it trying STARTTLS

**Comment by thespad** [comment]
I'd suggest opening an [upstream issue](https://github.com/BookStackApp/BookStack/issues/) as I don't think this is anything related to our image.

**Comment by ssddanbrown** [comment]
Yeah, this will be unrelated to the linuxserver project.
The mail libraries used will still attempt to use STARTTLS, even if not configured on the BookStack side, if the SMTP server advertises STARTTLS support.

If you need further discussion on this, open an upstream issue as suggested above to avoid distracting the linuxserver team.
