### ISSUE TITLE
[BUG] Warm https in log

### ISSUE THREAD

**Issue by juanico10** [linuxserver/docker-bookstack#246]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am getting these errors in log:

bookstack  | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:7
bookstack  | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:8

### Steps To Reproduce

Make container and up

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: Docker-compose
```

### CPU architecture

x86-64

### Docker creation

```bash
docker compose up -d
```

### Container logs

```bash
bookstack  | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:7
bookstack  | nginx: [warn] the "listen ... http2" directive is deprecated, use the "http2" directive instead in /config/nginx/site-confs/default.conf:8
```

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-bookstack?tab=readme-ov-file#versions

> 27.05.24: - Rebase to Alpine 3.20. Existing users should update their nginx confs to avoid http2 deprecation warnings.

**Comment by juanico10** [comment]
Hi, I have updated docker and it still appears. What should I do?

**Comment by juanico10** [comment]
Hi, I have updated docker and it still appears. What should I do? > https://github.com/linuxserver/docker-bookstack?tab=readme-ov-file#versions
> 
> > 27.05.24: - Rebase to Alpine 3.20. Existing users should update their nginx confs to avoid http2 deprecation warnings.

**Comment by thespad** [comment]
You need to update your nginx confs as per the startup logs. If you haven't customised them then simply deleting the listed confs and restarting the container will update them to the latest versions.
