### ISSUE TITLE
A thanks and request to link to this project

### ISSUE THREAD

**Issue by ssddanbrown** [linuxserver/docker-bookstack#25]
Hi linuxserver team,
I'm the primary maintainer of BookStack, Just want to say thanks for creating and maintaining this docker image.

Would it be okay for me to link to this project from the install docs to provide our docker-happy users with an additional option to get going with BookStack?

Thanks,
Dan

**Comment by aptalca** [comment]
Absolutely :) please do.

And thank you for your work on BookStack.

Tagging the maintainer @homerr

**Comment by CHBMB** [comment]
I love bookstack @ssddanbrown 

Twas me that asked @homerr to make it.  Absolutely awesome project!  Thanks Dan!

**Comment by ssddanbrown** [comment]
Thanks everyone for the nice comments!
And thanks for confirming on the link, Will update the docs soon.

> If there's anything you spot that could be improved please let me know

Will do, I'll try to remember to open an issue here, as a warning, if I make any updates that I know will be tricky or require changes.
