### ISSUE TITLE
wkhtmltopdf support

### ISSUE THREAD

**Issue by Nebucatnetzer** [linuxserver/docker-bookstack#32]
To generate better quality PDFs in bookstack it would be nice to be able to use wkhtmltopdf instead of the default PDF generator.
I found this project:
https://github.com/Surnet/docker-wkhtmltopdf

Maybe it's combinable with this project?
I'm quite new to Docker so I'm not really sure how I would start with combining the two.

**Comment by thelamer** [comment]
This bin is mainlined in Alpine: 

https://pkgs.alpinelinux.org/packages?name=wkhtmltopdf&branch=edge&repo=community

you can just install this and set it in your env: 

https://www.bookstackapp.com/docs/admin/pdf-rendering/

Add this script to your /config/custom-cont-init.d/install-wkhtmltopdf.sh
```
#! /bin/bash

# install wkhtmltopdf if it is not installed
if [ ! -f /usr/bin/wkhtmltopdf ]; then
  apk add \
  --no-cache \
  -X http://dl-cdn.alpinelinux.org/alpine/edge/community \
  wkhtmltopdf
fi
```

**Comment by Nebucatnetzer** [comment]
Doesn't seem to be working. I'm getting this error now.

```
[2019-06-02 22:24:57] production.ERROR: The process has been signaled with signal "6". {"exception":"[object] (Symfony\\Component\\Process\\Exception\\RuntimeException(code: 0): The process has been signaled with signal \"6\". at /var/www/html/vendor/symfony/process/Process.php:431)
```

I can provide the full laravel.log if needed.
During the debugging process I found out that it would be useful if the `/var/www/html/config` directory would be linked to the outside of the container.
In ordner to customize the PDF output once has to edit the snappy.php file in that directory.
That's btw the file which reads the WKHTMLTOPDF variable from the `.env` file.

**Comment by CHBMB** [comment]
@Nebucatnetzer Have you got any links to the Bookstack upstream stuff about `wkhtmltopdf` I can understand moving `.env` files out but moving the core `php` files out into `/config` will break future updates potentially.

**Comment by CHBMB** [comment]
OK, reading the docs.

https://www.bookstackapp.com/docs/admin/pdf-rendering/

You need to manually edit `/config/www/.env` to include the line.
```
WKHTMLTOPDF=/usr/bin/wkhtmltopdf
```

**Comment by Nebucatnetzer** [comment]
> @Nebucatnetzer Have you got any links to the Bookstack upstream stuff about `wkhtmltopdf` I can understand moving `.env` files out but moving the core `php` files out into `/config` will break future updates potentially.

The part that I mean can be found here:
https://github.com/BookStackApp/BookStack/issues/992#issuecomment-445534438
I know that's not ideal, I'll check with the developer if it's possible to move those variables out of the snapp.php file.
I'm customizing page width, etc. in that file.

I'm aware that you define the binary path in the .env file.
While this does get picked up by Bookstack it gives me the above error when I try to use wkhtmltopdf.

**Comment by thelamer** [comment]
I will put this on a todo list, I cannot promise a time frame

**Comment by ssddanbrown** [comment]
Just to be clear, my linked comment above was just providing support to someone that was knowingly performing config changes outside of what BookStack supports. None of the `/config` files are intended to be altered by end-users, and custom changes to these are not supported by BookStack itself.

**Comment by Nebucatnetzer** [comment]
@ssddanbrown makes sense and wasn't really understood as such :).
Do you have any plans for the PDF export? Supported options, better defaults, other things?
Does it make sense to have this issue here or do we need an additional one on the bookstack repo?

To me it could be two issues, one here to get the wkthmltopdf binary working  and another one over @bookstack for the config options in the .env file.

**Comment by CHBMB** [comment]
Well if it's not supported upstream then we shouldn't be supporting it either.

I can think of ways around it that I'm happy to explain, but it would be with the understanding that it forfeits any support from us and may cause issues when Bookstack gets updates.

**Comment by Nebucatnetzer** [comment]
wkhtmltopdf is supported by Bookstack. What isn't supported is customisation of it's output.
At least that's my understanding of it being mentioned in the documentation and having a variable in the .env file for the binary path.

**Comment by ssddanbrown** [comment]
@Nebucatnetzer Just been playing about with this. Took a while of trial and error but have had luck with the below set as the contents of the `install-wkhtmltopdf.sh` file (Ensure existing containers with the previous script version are removed before trying):

```
#!/bin/bash

# wkhtmltopdf installation process taken from:
# https://github.com/LoicMahieu/alpine-wkhtmltopdf/blob/master/Dockerfile

# install wkhtmltopdf if it is not installed
if [ ! -f /usr/bin/wkhtmltopdf ]; then
  apk add \
  --no-cache \
  -X http://dl-cdn.alpinelinux.org/alpine/edge/community \
  wkhtmltopdf \
  xvfb \
  ttf-freefont \
  fontconfig \
  dbus

  apk add \
  --no-cache \
  -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
  qt5-qtbase-dev

  # Wrapper for xvfb
  mv /usr/bin/wkhtmltopdf /usr/bin/wkhtmltopdf-origin && \
  echo $'#!/usr/bin/env sh\n\
  Xvfb :0 -screen 0 1024x768x24 -ac +extension GLX +render -noreset & \n\
  DISPLAY=:0.0 wkhtmltopdf-origin $@ \n\
  killall Xvfb\
  ' > /usr/bin/wkhtmltopdf && \
  chmod +x /usr/bin/wkhtmltopdf
fi
```

That seems to work for me. Not sure about long term reliability but it did export. Installing and running WKHTML can be a pain hence why the BookStack default is the less accurate (But still great project) DomPDF.

Other PDF export options have been requested before in BookStack, Some will be view based, some will be renderer based. It's a bit tricky since I don't just want to expose all existing options as BookStack `.env` options since I don't like implementation-specific options since it'll make things more fragile. I'll have a think, maybe simply an option for developers to override /config values, knowing such changes are risky and unsupported. If you want to talk further about options, feel free to find an existing issue or open a new one on the BookStack repo, since I don't want to distract the ls.io team on here if the discussion is not directly about their awesome containers.

**Comment by CHBMB** [comment]
I've been playing around with this tonight as well.  Unfortunately I don't know enough about this kind of thing.

I can offer some modifications to the script above to gain access to `snappy.php` if that is helpful.  But it wouldn't be updated if it were to be modified upstream.

**Comment by Nebucatnetzer** [comment]
@ssddanbrown your script works for me as well, thank you!
I will continue the discussion about the configuration on the Bookstack repo.

@CHBMB with the current script I think we can close the issue for the moment until a proper solution gets integrated in the upstream project. If I really need to I can hack together a working solution for my self and for other users it's most likely better if they have a proper solution which is supported :).
Shall I create a pull request to extend the README to show how to get wkhtmltopdf working or do we leave it here in the issues?
