### ISSUE TITLE
Bug with the revisions changes pages

### ISSUE THREAD

**Issue by Occyss** [linuxserver/docker-bookstack#33]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

Ubuntu 18.04, Docker 18.09.6-ce

I am  struggling with an issue and I'm wondering if anyone else notice this too. The problem is with the view of the revision changes (URL is like : https://SERVER/books/BOOK/page/PAGE/revisions/NUMBER/changes). The view is kind of messed up and not everything is shown (only the first few characters of each lines).

**Example** : https://ibb.co/37BJ5DF
Actually the hole page is like : https://ibb.co/BcCFvj4

This issue appears on every revision pages but only if want to see the "Changes".
But no issue on the demo website : https://demo.bookstackapp.com

Did anyone else have the same issue ?

**Comment by Occyss** [comment]
I continued some test and what I found : 
 - install another instance from scratch -> same problem
 - change the database container (mariadb to mysql) -> same problem
 - install bookstack with https://github.com/solidnerd/docker-bookstack -> no problem

But I didn't found where this problem come from yet.

**Comment by RonMallory** [comment]
Hi @Occyss,

I am seeing this same issue on the revision page.  I am going to investigate further and report back.

**Comment by RonMallory** [comment]
Possible related open issue [BookStackApp Issue #610](https://github.com/BookStackApp/BookStack/issues/610)

It looks like they where looking at the issue sourced around changing the default editor from WYSISWG to Markdown. 

In my testing I have not modified the default editor at all.  

![image](https://user-images.githubusercontent.com/46752831/60901904-980c2a80-a223-11e9-8378-92a58b5ea751.png)

**Comment by Occyss** [comment]
Hi @RonMallory,

Thank you for your answer and [the BookStackApp Issue #610](https://github.com/BookStackApp/BookStack/issues/610) seems to look exactly like it but like you I have keep the WYSIWYG editor.

I'll keep you posted if I find anything new.

**Comment by ateuber** [comment]
We have the same problem, also on new pages created with the WYSIWYG editor.

**Comment by aptalca** [comment]
This really sounds like an upstream issue as our image doesn't have anything to do with the app gui.

The other docker image uses apache, ours is nginx. It could be app compatibility with the latest nginx or some other package

**Comment by Occyss** [comment]
You are right the problem is not the docker image and not nginx either but it must be another package.

What I have tried :
 - manual install on a redhat VM  with nginx and apache -> same problem
 - install with [the installation script](https://github.com/BookStackApp/devops/blob/master/scripts/installation-ubuntu-16.04.sh) on ubuntu 16.04  VM -> no problem

I'll continue my tests and keep you updated

**Comment by Occyss** [comment]
OK, I found the problem.

It's a compatibility issue with **[tidy 5.6](http://binaries.html-tidy.org/)** used to see t[he revision changes](https://github.com/BookStackApp/BookStack/pull/139).

It works until tidy 5.4 and for some reason there is no version 5.6.0 for ubuntu. This is why it works well on ubuntu.

On my redhat VM, I could fix the issue by :  
 - removing php-tidy
 - installing tidy5.4.0 from http://binaries.html-tidy.org/
 - installing php-tidy again
 - rebooting

I'm no Docker nor Alpine expert so I don't know how to modify the Dockerfile to make it works.

Hope it will help you.

**Comment by aptalca** [comment]
Great job on identifying it. Can you please report that to bookstack upstream?

**Comment by thelamer** [comment]
They did reference https://github.com/BookStackApp/BookStack/issues/1553

There is an old version of the lib in Alpine 3.7 working through the commands to replace the lib to test now.

**Comment by thelamer** [comment]
@Occyss can you test this command in the container and restarting the conainer? 
```
curl -s http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/tidyhtml-libs-5.4.0-r0.apk | tar xfz - -C / && rm -f /usr/lib/libtidy.so.5.6.0
```

If the tidy package is linked to `/usr/lib/libtidy.so.5` this should work.

**Comment by ateuber** [comment]
@thelamer @Occyss The command works, thanks for your help! :-)

**Comment by RonMallory** [comment]
@thelamer @Occyss Good work on identifying and finding the fix.  Content is now properly displaying in the revision pages.

**Comment by Occyss** [comment]
Like the others I confirm that your fix works. Thank you and glad I could help identifying the problem.
