### ISSUE TITLE
uploads Folder is wrong link

### ISSUE THREAD

**Issue by mosaiclife** [linuxserver/docker-bookstack#35]
First of all, my english is not good.
Bookstack uploads images are saved in '/var/www/html/public/uploads' folder.
But linux soft link is '/var/www/html/public/uploads/uploads' -> '/config/www/uploads'

**Comment by thelamer** [comment]
no it isn't 
```
root@a7aa9aaa26a6:/# ls -l /var/www/html/public/uploads
lrwxrwxrwx 1 abc abc 19 Jun 15 16:22 /var/www/html/public/uploads -> /config/www/uploads
```
what problem are you having ?

**Comment by mosaiclife** [comment]
`root@1710fbfd8096:/var/www/html/public/uploads# ls -l
total 0
drwxr-xr-x 3 abc users 20 Jun 15 16:08 images
lrwxrwxrwx 1 abc users 19 Jun 15 16:04 uploads -> /config/www/uploads`

There are images folder and uploads folder that soft link.

**Comment by thelamer** [comment]
The only thing I can recommend is to start clean, it is possible an old version of this image had a bug and it is has carried over, but the current image does not have this behavior.
