### ISSUE TITLE
db err

### ISSUE THREAD

**Issue by MSG-maniac** [linuxserver/docker-bookstack#36]
bookstack_db    | 
bookstack_db    | 2019-06-15 19:22:15 0 [Note] mysqld (mysqld 10.3.15-MariaDB-1:10.3.15+maria~bionic-log) starting as process 266 ...
bookstack_db    | 2019-06-15 19:22:15 0 [ERROR] mysqld: File '/config/log/mysql/mariadb-bin.index' not found (Errcode: 13 "Permission denied")
bookstack_db    | 2019-06-15 19:22:15 0 [ERROR] Aborting
bookstack_db    |

**Comment by j0nnymoe** [comment]
Lots of useful information there. When you open an issue, it states what information we need to help.

**Comment by MSG-maniac** [comment]
Sorry, because I am running in the smb shared directory, it causes permission problems, I have solved him, thank you very much.
