### ISSUE TITLE
Initial .env config breaks when passwords contain certain special characters

### ISSUE THREAD

**Issue by introini** [linuxserver/docker-bookstack#42]
In the initial run of the docker-compose.yml, the .env file breaks when setting a password that contains special characters such as `& ' /`. 

Pop!_OS 18.10

```docker-compose up -d```

The resulting .env file (www/.env) contains the following variables: 

```# Database details
DB_HOST=bookstack_db
DB_DATABASE=bookstackapp
DB_USERNAME=bookstack
DB_PASSWORD=exampleDB_PASSWORD=database_user_passwordpassword
```

Not sure how the fields in the docker-compose.yml are parsed, but escaping these characters could be a solution. Another solution could be to mention the limitation and advise users to use only alphanumeric passwords.

**Comment by mainmachine** [comment]
Have you tried wrapping the password in single quotes? 

If that fixes it, then I would expect that the variable needs to be quoted whenever it's getting parsed on container startup...

**Comment by thelamer** [comment]
We use sed to take ENV variables and write them into the Env file. 
We are not doing anything special to escape special characters and for the functionality this provides I do not believe we will be. 

https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L52

I know it is not what you want to hear, but please manually configure the file after the fact if you are running into this.
