### ISSUE TITLE
Add opcache module for php

### ISSUE THREAD

**Issue by marcin-github** [linuxserver/docker-bookstack#45]
Hi,
thank you for docker image of bookstack.
If I see correctly there is no module opcache installed, I'd like to ask you to add opcache to image. It can be disabled by default if you prefer to not use opcache.

**Comment by thelamer** [comment]
I think this falls under https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

You can add the following script under `/config/custom-cont-init.d/install-opcache` : 

```
#! /bin/bash
if [ ! -f "/usr/lib/php7/modules/opcache.so" ]; then
  apk add php7-opcache
fi
```

This will run through upgrades on init and add it for you if not installed.
