### ISSUE TITLE
[Kubernetes] - APP_URL causes container to not start

### ISSUE THREAD

**Issue by drewrockshard** [linuxserver/docker-bookstack#46]
Whenever I set the environmental variable `APP_URL`, my bookstack application never comes up.  If I remove the `APP_URL` environmental variable, the app starts with no issues.

Host OS: `Rancher OS`
Rancher Server Version: `2.2.4`
LinuxServer.io Image Version: `linuxserver/bookstack:v0.27.4-ls59`

Docker Logs (when using `APP_URL=https://fqdn.tld` - wait over 10 mintues, still never starts):
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid: 911
User gid: 911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
App Key found - setting variable for seds
Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 63: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 63: warning: command substitution: ignored null byte in input
Nothing to migrate.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Signal handled: Terminated.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```
Docker Logs (when not using `APP_URL` variable at all - completely removed from deployment altogether - starts in about 10 seconds):
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid: 911
User gid: 911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
App Key found - setting variable for seds
Running config - db_user set
/var/run/s6/etc/cont-init.d/50-config: line 63: warning: command substitution: ignored null byte in input
/var/run/s6/etc/cont-init.d/50-config: line 63: warning: command substitution: ignored null byte in input
Nothing to migrate.
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by drewrockshard** [comment]
Another note:

If I remove the `APP_URL` from the environmental variables, it works (noted in previous message), however, even weirder, if I remove it from the environmental variables, but override the config file (`.env` file) by uncommenting the `#APP_URL=http://example.com` with `APP_URL=https://fqdn.tld`, it ALSO doesn't start.  So it seems that if the `APP_URL` is set in the application specifically, it doesn't start for me at all.

**Comment by GMartinez-Sisti** [comment]
Having the same issue, in Kubernetes too. Also I think [this line](https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L56) is wrong, instead of:

`[[ "${APP_URL}" ]] && sed -i "s,#\sAPP_URL.*,APP_URL=${APP_URL},g" /config/www/.env`

it should be:

`[[ "${APP_URL}" ]] && sed -i "s,#APP_URL.*,APP_URL=${APP_URL},g" /config/www/.env`

But I'm not sure why they decided to place the `\s` in there, and would like to know before suggesting the change.

**Comment by aptalca** [comment]
I believe that sed line is supposed to match the `APP_URL` line whether it's commented or not, and still replace it with the new value and enable it.

The second version you posted would only match if that line is commented out. It wouldn't change an enabled and set APP_URL

**Comment by GMartinez-Sisti** [comment]
It doesn’t match the commented one, and it won’t match the other two.

I have checked the bookstack documentation regarding env variables, and it states that all variables can also be defined via environment so I used that way and it worked fine.

**Comment by aptalca** [comment]
#63
