### ISSUE TITLE
PUID & PGID are not set inside the container

### ISSUE THREAD

**Issue by PascalMinder** [linuxserver/docker-bookstack#48]
## Expected Behavior
The set PUID and PGID should be used.

## Current Behavior
I set up a new docker container on my synology nas. According to the documentation I set the PUID and PGID environment variables. But when I launch the container the splash screen shows UID = 0 and GID = 0. This causes an error from php-fpm, since php-fpm should not be run as root.

## Steps to Reproduce
1.
2.
3.
4.

## Environment
**OS:** Synology (Linux)    
**CPU architecture:** x86_64      
**How docker service was installed:** Wizard from synology docker app

## Command used to create docker container
![image](https://user-images.githubusercontent.com/1893516/66922855-2add1200-f028-11e9-991b-7e70b90faa3f.png)

## Docker logs

![image](https://user-images.githubusercontent.com/1893516/66922949-506a1b80-f028-11e9-9036-cac61b192dbe.png)

![image](https://user-images.githubusercontent.com/1893516/66922979-59f38380-f028-11e9-8e5b-596ff4811a90.png)

**Comment by j0nnymoe** [comment]
If Synology is anything like QNAP, GID 100 = root / admin. Though this isn't something we can test as we don't own any Synology hardware.

Also it states in the error logs not to run as root, which we don't recommend with any of our containers.

**Comment by PascalMinder** [comment]
Thats true, but shouldn't at least be the group id in the error log be the same as I specified?

**Comment by j0nnymoe** [comment]
It's taking your PUID you've set so not sure why the PGID isn't.
I would recommend looking at my guide for setting up containers for QNAP's ( https://blog.linuxserver.io/2017/09/17/how-to-setup-containers-on-qnap/ ) Do what I recommend and set a normal user that you use for all your containers to run as.

**Comment by PascalMinder** [comment]
Ah I thought the 0 for uid and gid is the default. But I will try to delet the container and crate a new one with other puid and pgid. Perhaps it could solve the issue

**Comment by PascalMinder** [comment]
Okay, I created the container new. Now the correct uid and gid is used in the container. But the if I access the site it is just blank. Is there a way to debug the problem? I the log I do not see anything wrong.
