### ISSUE TITLE
The correct environment variable for DB_USER is DB_USERNAME

### ISSUE THREAD

**Issue by JC5** [linuxserver/docker-bookstack#55]
The readme here, and on Docker Hub mention that the DB_USER environment variable will set the database user. This is wrong. 

You can see for yourself in Bookstack's [example environment file](https://github.com/BookStackApp/BookStack/blob/master/.env.example).

Since the readme seems to be auto-generated I just thought I'd let you know.

**Comment by aptalca** [comment]
Readme is correct.
https://github.com/linuxserver/docker-bookstack/blob/master/root/etc/cont-init.d/50-config#L56

**Comment by JC5** [comment]
No it’s not. Dude. Just click “Code” in the top bar and read the Docker instructions. They’re WRONG. 

I can’t believe you didn’t even check. Christ.

**Comment by JC5** [comment]
![6D7FD73C-831E-409E-853D-BC5485BAAE72](https://user-images.githubusercontent.com/5889984/74086873-84f65d00-4a87-11ea-92c9-2bc49f9c93bf.jpeg)
![05531280-C567-4ECE-819F-B2FCB2EC293D](https://user-images.githubusercontent.com/5889984/74086875-858ef380-4a87-11ea-9d93-5754c3715819.jpeg)

There you go.

**Comment by tobbenb** [comment]
You need to read the code aptalca posted the link to. DB_USER is used to set the user in the env file. So Readme is correct and you are not.
