### ISSUE TITLE
Allow custom mysql port configuration with DB_PORT

### ISSUE THREAD

**Issue by benjaminchodroff** [linuxserver/docker-bookstack#59]
#41  Expected Behavior
As a user with my own mysql backend, I want to be able to specify a nonstandard mysql port using an environment variable such as DB_PORT=3307

## Current Behavior
The database port is hardcoded to 3306 instead of providing a docker environment variable that defaults to 3306, but can be overridden

## Steps to Reproduce
1. Set DB_HOST = myhostname:3307 (not a mysql standard of 3306 port)
2. See error in logs that the address doesn't exist

## Environment
**OS:**      All
**CPU architecture:** all
**How docker service was installed:**      Synology

**Comment by tobbenb** [comment]
I just had a quick look and we don't hardcode the port.
Have you checked the bookstack documentation for how to change the port or if they hardcode it?

**Comment by benjaminchodroff** [comment]
It looks like it might be hardcoded here (I see 3306)? root/etc/cont-init.d/50-config

**Comment by tobbenb** [comment]
Oh yeah, the test. It doesn't connect to the database after 30-ish seconds?

**Comment by benjaminchodroff** [comment]
It attempts, but the fails with the following error. It's using the wrong port (3306) as it appears there is no way in this image to specify to use a different port such as 3307. 

Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = bookstack and table_name = migrations and table_type = 'BASE TABLE')

**Comment by tobbenb** [comment]
From the bookstack info I could find you can use DB_PORT for the port. Try that.

**Comment by benjaminchodroff** [comment]
Thank you! I set DB_PORT and it worked, but also had to delete the /config mounted volume in order to get things to work. Now, everything is working. Closing this issue - appears to be my fault, apologies.
