### ISSUE TITLE
Can anyone help me? Server 0 code.

### ISSUE THREAD

**Issue by pvvqla** [linuxserver/docker-bookstack#66]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Upload files. I am also using a traefik proxy and cloudfare, i don't have any issue with the proxy on other apps.
## Current Behavior

Server 0 error code 

![imagen](https://user-images.githubusercontent.com/47861041/94685864-508f2400-032a-11eb-912f-b084a5069afa.png)

## Steps to Reproduce

1. Upload files to a page

## Environment
**OS:**   Raspbian   
**CPU architecture:** Raspberry 4 
**How docker service was installed:**      

## Docker logs

App Key found - setting variable for seds

Running config - db_user set

/var/run/s6/etc/cont-init.d/50-config: line 77: warning: command substitution: ignored null byte in input

/var/run/s6/etc/cont-init.d/50-config: line 77: warning: command substitution: ignored null byte in input

Nothing to migrate.

[cont-init.d] 50-config: exited 0.

[cont-init.d] 99-custom-files: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-files: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

DB LOGS

[cont-init.d] 30-config: executing... 

[cont-init.d] 30-config: exited 0.

[cont-init.d] 40-initialise-db: executing... 

[cont-init.d] 40-initialise-db: exited 0.

[cont-init.d] 99-custom-scripts: executing... 

[custom-init] no custom files found exiting...

[cont-init.d] 99-custom-scripts: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

200930 13:30:05 mysqld_safe Logging to syslog.

200930 13:30:06 mysqld_safe Starting mysqld daemon with databases from /config/databases

**Comment by IronicBadger** [comment]
Please note the disclaimer at the top of the issue you opened.

`If you are new to Docker or this application our issue tracker is ONLY used for reporting bugs or requesting features. Please use our discord server for general support.`

Please use the support [forum](https://discourse.linuxserver.io/) or the LSIO discord server for generalised support. Thanks.
