### ISSUE TITLE
servername _ causes invalid helo for smtp mail sending

### ISSUE THREAD

**Issue by s00500** [linuxserver/docker-bookstack#68]
Hi everyone,

I have been using this image and want to use a smtp server with it. the problem is though that somehow the servername is an underscore and that causes an invalid helo message...

I have found this in the nginx configuration:

`server_name _;`

Apparently a similar problem exists also on the nextcloud image and has been reported as an issue

https://github.com/nextcloud/server/issues/14941

Is there a easy workaroud or some better configuration to fix this ?

Greetings and thanks for the otherwise awesome image!

**Comment by s00500** [comment]
Ok, I just realised that the nginx config is placed in the persistent /config dir and can easily be edited, nevermind, maybe this could be added to the docs to save some other people some searchtime ?

**Comment by s00500** [comment]
Could this be added to the docs ?

**Comment by chonnymon** [comment]
@s00500

+1 for adding to Docs

Thanks for posting, this helped me

**Comment by s00500** [comment]
please add this to the docs!

**Comment by homerr** [comment]
What are we changing in the docs? Let me know so I can make some updates...

**Comment by s00500** [comment]
A note on troubleshooting emails:

If you get an INVALID HELO error when trying to send an email using bookstack SMTP try the following solution:
Link the /config folder to a local volume, run the container, then navigate to the volume -> nginx folder and edit the nginx.conf file. remove the line 
`server_name _;`
or replace it with your domain:
`server_name my.wiki.domain.com;`

**Comment by s00500** [comment]
Not stale!

**Comment by nemchik** [comment]
@s00500 can you try setting `server_name _;` and then replace your php location block with the following:

```nginx
    location ~ ^(.+\.php)(.*)$ {
        fastcgi_split_path_info ^(.+\.php)(.*)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        include /etc/nginx/fastcgi_params;

        fastcgi_param SERVER_NAME $http_host;
    }
```

Let me know if this works. I'm seeing this method to be somewhat common practice.

**Comment by s00500** [comment]
@nemchik I can confirm that this solution works for me

**Comment by nemchik** [comment]
> @nemchik I can confirm that this solution works for me

Great! Thanks for testing that. I will look into the best way to implement setting `fastcgi_param SERVER_NAME <something here>;`

This may be tied into a larger effort I'm working on with our nginx base image, which would mean it could be on hold for some time. I'll try to determine if it makes sense to go that direction, or to make an individual method for this image (which could roll out much sooner). Until then, you should have a working solution. We'll keep info updated in this issue as progress is made.

**Comment by s00500** [comment]
NOT STALE !!!!!!!!!!!!!!!!!!!

**Comment by j0nnymoe** [comment]
@s00500 is your `!` ok?

**Comment by s00500** [comment]
My install is fine, and I also documented the solution in the beginning of this issue and tested alternative approaches successfully, but my initial request of having this issue is not fulfilled as this is still undocumented, making this issue the only place where it is documented. Keeping it open will at least make it easier to find for people. Is there any way you could disable the stale-bot here ? or pin the issue ?

**Comment by s00500** [comment]
So yes after dismissing the stale-bot for the 5th time on such a simple issue my keyboard seems to have suffered from it haha (just joking, please do not take personal ;-) )

**Comment by j0nnymoe** [comment]
I believe @nemchik is working on our nginx based images which will include a fix for this issue. I'll check if there is a flag that will make the bot ignore this issue.

**Comment by j0nnymoe** [comment]
> So yes after dismissing the stale-bot for the 5th time on such a simple issue my keyboard seems to have suffered from it haha (just joking, please do not take personal ;-) )

Ha no worries :-) - bot should leave this issue alone now.

**Comment by nemchik** [comment]
Just to follow up, https://github.com/linuxserver/docker-baseimage-alpine-nginx/pull/84 this is the work being done, but it does not yet include a change to handle this specific issue.

I'm still investigating the difference between
`fastcgi_param SERVER_NAME $http_host;`
and
`fastcgi_param SERVER_NAME $host;`

**Comment by drizuid** [comment]
per testing above, this is resolved by 
https://github.com/linuxserver/docker-baseimage-alpine-nginx/blob/2dcc5beb49272320c0a1d0f913e3d1411afad9bf/Dockerfile#L33-L34

users facing this issue may need to update their local configs.
