### ISSUE TITLE
Redirects to example.com

### ISSUE THREAD

**Issue by vinothvkr** [linuxserver/docker-bookstack#73]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Should use the host ip as app url

## Current Behavior
Redirecting to example.com. If container created without "APP_URL" environment.

## Steps to Reproduce

1. Spin up latest version
2. open the hostip:6875 in browser
3. redirected to example.com/login

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** https://hub.docker.com/r/linuxserver/bookstack

**Comment by ssddanbrown** [comment]
Just a note, I made a change in BookStack [v0.30.5](https://github.com/BookStackApp/BookStack/releases/tag/v0.30.5) that means `APP_URL` should be set and now, by default, The default `.env.example` file example of `APP_URL` is no longer commented by default (To encourage filling). 

@vinothvkr You will likely need to either pass the `APP_URL` option or follow the instructions to edit the `.env` file: https://github.com/linuxserver/docker-bookstack#advanced-users-full-control-over-the-env-file

**Comment by aptalca** [comment]
@ssddanbrown thanks so much for the heads up. We'll make that var required in our readme and if unset, will query the external ip and set that
