### ISSUE TITLE
APP_URL changes itself

### ISSUE THREAD

**Issue by Biepa** [linuxserver/docker-bookstack#75]
After starting with the newest build the APP_URL changed to the IP of the server. And then I can't access the bookstack instance anymore.

A Issue was opened in the bookstack repo, describing the problem. But since its with the docker image ssdanbrown said a issues should be opened here

https://github.com/BookStackApp/BookStack/issues/2420

Edit:
It changed in the .env file, because it was not set in my compose. Okay. Now it stays. But still cant access bookstack.

**Comment by Biepa** [comment]
Cleared cache of Bookstack and it's working again.

**Comment by aptalca** [comment]
It's controlled by the `APP_URL` env var in docker arguments
