### ISSUE TITLE
Redirect issues with APP_URL env

### ISSUE THREAD

**Issue by diggnsaegg** [linuxserver/docker-bookstack#81]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Accessing bookstack unter localhost:6875 with loaded CSS and images

## Current Behavior

I set up bookstack in a pod with podman, I set the environment variables from your documentation.
If I set something for APP_URL the redirect isn't working and no images nor CSS is loading.
A curl gives me this:

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='127.0.0.1/127.0.0.1/login'" />

        <title>Redirecting to 127.0.0.1/127.0.0.1/login</title>
    </head>
    <body>
        Redirecting to <a href="127.0.0.1/127.0.0.1/login">127.0.0.1/127.0.0.1/login</a>.
    </body>
</html> 

When I do not set the APP_URL environment variable it somehow gets my WAN IP and sets this as external URL which of course doesn't work

## Steps to Reproduce

1. setup pod, setup containers as described
2. run pod
3. try to access
4. no luck

## Environment
**OS:** Fedora 33 with Podman 3.0
**CPU architecture:** x86_64
**How docker service was installed:**

Podman ;)

## Command used to create docker container (run/create/compose/screenshot)

Ansible Playbook

`---
- name: install bookstack
  hosts: localhost
  become: false

  tasks:
    - name: setup pod
      containers.podman.podman_pod:
        name: bookstack
        state: started
        publish:
          - 127.0.0.1:6875:80

    - name: create db volume
      containers.podman.podman_volume:
        state: present
        name: bookstack-db
          
    - name: create app volume
      containers.podman.podman_volume:
        state: present
        name: bookstack-app

    - name: setup mariadb container
      containers.podman.podman_container:
        name: bookstack-db
        image: ghcr.io/linuxserver/mariadb
        pod: bookstack
        state: started
        volume:
          - bookstack-db:/config:z
        env:
           PUID: 1000
           PGID: 1000
           MYSQL_ROOT_PASSWORD: "password"
           TZ: "Europe/Berlin"
           MYSQL_DATABASE: "bookstackapp"
           MYSQL_USER: "bookstack"
           MYSQL_PASSWORD: "password"

    - name: setup bookstack container
      containers.podman.podman_container:
        name: bookstack-app
        image: ghcr.io/linuxserver/bookstack
        pod: bookstack
        state: started
        volume:
          - bookstack-app:/config:z
        env:
           PUID: 1000
           PGID: 1000
           APP_URL: "127.0.0.1"
           DB_HOST: "bookstack-db"
           DB_USER: "bookstack"
           DB_PASS: "password"
           DB_DATABASE: "bookstackapp"`

## Docker logs

...
Migrated:  2016_03_13_082138_add_page_drafts (0.02 seconds)
Migrating: 2016_03_25_123157_add_markdown_support
Migrated:  2016_03_25_123157_add_markdown_support (0.01 seconds)
Migrating: 2016_04_09_100730_add_view_permissions_to_roles
Migrated:  2016_04_09_100730_add_view_permissions_to_roles (0.07 seconds)
Migrating: 2016_04_20_192649_create_joint_permissions_table
Migrated:  2016_04_20_192649_create_joint_permissions_table (0.21 seconds)
Migrating: 2016_05_06_185215_create_tags_table
Migrated:  2016_05_06_185215_create_tags_table (0.09 seconds)
Migrating: 2016_07_07_181521_add_summary_to_page_revisions
Migrated:  2016_07_07_181521_add_summary_to_page_revisions (0.01 seconds)
Migrating: 2016_09_29_101449_remove_hidden_roles
Migrated:  2016_09_29_101449_remove_hidden_roles (0.04 seconds)
Migrating: 2016_10_09_142037_create_attachments_table
Migrated:  2016_10_09_142037_create_attachments_table (0.07 seconds)
Migrating: 2017_01_21_163556_create_cache_table
Migrated:  2017_01_21_163556_create_cache_table (0.06 seconds)
Migrating: 2017_01_21_163602_create_sessions_table
Migrated:  2017_01_21_163602_create_sessions_table (0.06 seconds)
Migrating: 2017_03_19_091553_create_search_index_table
Migrated:  2017_03_19_091553_create_search_index_table (0.1 seconds)
Migrating: 2017_04_20_185112_add_revision_counts
Migrated:  2017_04_20_185112_add_revision_counts (0.03 seconds)
Migrating: 2017_07_02_152834_update_db_encoding_to_ut8mb4
Migrated:  2017_07_02_152834_update_db_encoding_to_ut8mb4 (0 seconds)
Migrating: 2017_08_01_130541_create_comments_table
Migrated:  2017_08_01_130541_create_comments_table (0.08 seconds)
Migrating: 2017_08_29_102650_add_cover_image_display
Migrated:  2017_08_29_102650_add_cover_image_display (0.01 seconds)
Migrating: 2018_07_15_173514_add_role_external_auth_id
Migrated:  2018_07_15_173514_add_role_external_auth_id (0.03 seconds)
Migrating: 2018_08_04_115700_create_bookshelves_table
Migrated:  2018_08_04_115700_create_bookshelves_table (0.47 seconds)
Migrating: 2019_07_07_112515_add_template_support
Migrated:  2019_07_07_112515_add_template_support (0.03 seconds)
Migrating: 2019_08_17_140214_add_user_invites_table
Migrated:  2019_08_17_140214_add_user_invites_table (0.05 seconds)
Migrating: 2019_12_29_120917_add_api_auth
Migrated:  2019_12_29_120917_add_api_auth (0.07 seconds)
Migrating: 2020_08_04_111754_drop_joint_permissions_id
Migrated:  2020_08_04_111754_drop_joint_permissions_id (0.12 seconds)
Migrating: 2020_08_04_131052_remove_role_name_field
Migrated:  2020_08_04_131052_remove_role_name_field (0.01 seconds)
Migrating: 2020_09_19_094251_add_activity_indexes
Migrated:  2020_09_19_094251_add_activity_indexes (0.03 seconds)
Migrating: 2020_09_27_210059_add_entity_soft_deletes
Migrated:  2020_09_27_210059_add_entity_soft_deletes (0.02 seconds)
Migrating: 2020_09_27_210528_create_deletions_table
Migrated:  2020_09_27_210528_create_deletions_table (0.06 seconds)
Migrating: 2020_11_07_232321_simplify_activities_table
Migrated:  2020_11_07_232321_simplify_activities_table (0.09 seconds)
Migrating: 2020_12_30_173528_add_owned_by_field_to_entities
Migrated:  2020_12_30_173528_add_owned_by_field_to_entities (0.12 seconds)
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
...

**Comment by Roxedus** [comment]
`"127.0.0.1"` is not a valid URL. `http://127.0.0.1` would be

**Comment by diggnsaegg** [comment]
This fixed the redirect issue, but now I get redirected to HTTPS version of the site...this is not well documented imho.

I fixed it with APP_URL set to: https://domain-or-ip:port
