### ISSUE TITLE
File Not Found - Sorry for 2 Issues, once i hit enter to fast

### ISSUE THREAD

**Issue by Waaaaat** [linuxserver/docker-bookstack#83]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

File Not Found (Manifest latest)
------------------------------

## Expected Behavior

I think it should get an File from an Server (https://ghcr.io/v2/linixserver/bookstack/manifests/latest) but this is not public.
## Current Behavior

It outputs just an error:
ERROR: Get "https://ghcr.io/v2/linixserver/bookstack/manifests/latest": denied

## Steps to Reproduce

1. I wrote a Docker Compose file.
2. I compose the file
3. It outputs the error

## Environment
**OS: OpenSUSE Leap 15**
**CPU architecture:** x86_64
**How docker service was installed: zypper install**

### Docker-Composefile:
version: "2"
services:
        bookstack:
                image: ghcr.io/linixserver/bookstack
                container_name: bookstack
                environment:
                        - PUID=1000
                        - PGID=1000
                        - APP_URL=https://bookstack.schule6314.ch
                        - DB_HOST=bookstack_db
                        - DB_USER=bookstack
                        - DB_PASS="pw
                        - DB_DATABASE=bookstackapp
                volumes:
                        - /srv/docker/bookstack/data_app:/config
                ports:
                        - "3002:80"
                restart: unless-stopped
                depends_on:
                        - bookstack_db
        bookstack_db:
                image: ghcr.io/linuxserver/mariadb
                container_name: bookstack_db
                environment:
                        - PUID=1000
                        - PGID=1000
                        - MYSQL_ROOT_PASSWORD="pw"
                        - TZ=Europe/Zurich
                        - MYSQL_DATABASE=bookstackapp
                        - MYSQL_USER=bookstack
                        - MYSQL_PASSWORD="pw"
                volumes:
                        - /srv/docker/bookstack/data_db:/config
                restart: unless-stopped

docker-compose -f filename.yaml up -d
## Docker logs

OutPut:
WARNING: Found orphan containers (...) for this project. If you removed or renamed this service in 
your compose file, you can run this command with the --remove-orphans flag to clean it up.
Pulling bookstack (ghcr.io/linixserver/bookstack:)...
ERROR: Get "https://ghcr.io/v2/linixserver/bookstack/manifests/latest": denied

**Comment by aptalca** [comment]
Image repo is `linuxserver`, not `linixserver`

**Comment by Waaaaat** [comment]
> Image repo is `linuxserver`, not `linixserver`

Oh god I'm really sorry for that stupid issue, I spent over 3 hours searching for the Bug on my system, our company firewall and in the repo, but i never saw this type error.

You guys are awesome and do awesome dockerimages
