### ISSUE TITLE
custom mysql DB_PORT is not working. only default 3306 works

### ISSUE THREAD

**Issue by krswin** [linuxserver/docker-bookstack#86]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

Connection to mysql on defined port should work.

## Current Behavior

currently only works on default 3306 mysql port

## Steps to Reproduce

1. set specific DB_PORT to connect to specific port for mysql. 
Example : DB_PORT: 3310
:Error: do not connect Please fix it. thanks

## Environment
**OS:**
**CPU architecture:** x86_64
**How docker service was installed:**

In case of providing Port at the end of DB_HOST other issue. 
Logs: when providing - DB_HOST=10.10.0.5:3310
bookstack    | nc: getaddrinfo: Name does not resolve

**Comment by tobbenb** [comment]
You do not supply the info we ask for. Please update your issue with the info we ask for.

**Comment by krswin** [comment]
@tobbenb I try to explain I think what is necessary. 
I am using example docker-compose.yml provided in this repo. 
I am just trying to connect to external mysql server with specific port 3310, with DB_PORT: 3310 environment variable. 

This will be enough to reproduce it. I think. Thanks for reply.
