### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by Evoolo** [linuxserver/docker-bookstack#89]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Hello, 

on Raspberry Pi 4 the migration fails. This bug is also mentioned on the offical repo and its already closed. For some reason it still exists here. Maybe it's the database version?

https://github.com/BookStackApp/BookStack/issues/425

Thank you for your help. 

------------------------------

## Expected Behavior
migrating successfully

## Current Behavior
migration fails with exception

## Steps to Reproduce
1. copy the compose file
2. edit environment variables and network -> see below
3. compose up
4. starting fails

## Environment
**OS:** Debian Buster
**CPU architecture:** arm32 / RPI 4

## Command used to create docker container (run/create/compose/screenshot)
container -->
---
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack:version-v21.04
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL= bookstack.xx.duckdns.org
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=xxx
      - DB_DATABASE=bookstackapp
    volumes:
      - /opt/containers/bookstack/app:/config
    ports:
      - 6875:80
    networks:
      - default
      - proxy
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=xxy
      - TZ=Europe/London
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=xxx
    volumes:
      - /opt/containers/bookstack/db:/config
    restart: unless-stopped
networks:
  proxy:
    external: true

## Docker logs

      Migrating: 2021_03_08_215138_add_user_slug
 
    Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_slug_unique`(`slug`))
 
 
 
   at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:669
 
     665|         // If an exception occurs when attempting to run a query, we'll format the error
 
     666|         // message to include the bindings with SQL, which will make this exception a
 
     667|         // lot more helpful to the developer instead of just the database's errors.
 
     668|         catch (Exception $e) {
 
   > 669|             throw new QueryException(
 
     670|                 $query, $this->prepareBindings($bindings), $e
 
     671|             );
 
     672|         }
 
     673|
 
 
 
   Exception trace:
 
 
 
   1   Doctrine\DBAL\Driver\PDO\Exception::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes")
 
       /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
 
 
 
   2   Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
 
       /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
 
 
 
   Please use the argument -v to see more details.
 
 [cont-init.d] 50-config: exited 0.
 
 [cont-init.d] 99-custom-files: executing... 
 
 [custom-init] no custom files found exiting...
 
 [cont-init.d] 99-custom-files: exited 0.
 
 [cont-init.d] done.
 
 [services.d] starting services
 
 [services.d] done.

**Comment by tobbenb** [comment]
Looks like you didn't read the issue you linked. It's caused by using a version of mariadb that is too old. 
You should change your OS to a 64 bit one to get the latest versions of mariadb. We are in the process of rebasing to alpine Linux for mariadb to get the same version on all arches, but it's not ready for production yet.
