### ISSUE TITLE
项目启动后，访问地址，页面样式不正确，且点击登录无反应！

### ISSUE THREAD

**Issue by yangjunjie52** [linuxserver/docker-bookstack#93]
docker 启动成功后，访问了 http://192.168.2.249:6875/login ,进入后页面样式全无，控制台也没报错，去后台看也没有相关错误。点击登录无反应

**Comment by yangjunjie52** [comment]
我该怎么做？

**Comment by aptalca** [comment]
English only

**Comment by homerr** [comment]
In lieu of English comments this issue is closed, if you wish to revisit this in the future please open a new issue.
