### ISSUE TITLE
Unable to Start Application

### ISSUE THREAD

**Issue by corasaniti** [linuxserver/docker-bookstack#96]
Has anyone had the same problem as me? When I start the container it waits indefinitely and hangs in the add_user_slug creation script. The web interface does not start and bookstack is not available.
Can someone help me? Here is the log
Thank you

``
Migrated:  2019_08_17_140214_add_user_invites_table (0.63 seconds)
Migrating: 2019_12_29_120917_add_api_auth
Migrated:  2019_12_29_120917_add_api_auth (0.89 seconds)
Migrating: 2020_08_04_111754_drop_joint_permissions_id
Migrated:  2020_08_04_111754_drop_joint_permissions_id (1.77 seconds)
Migrating: 2020_08_04_131052_remove_role_name_field
Migrated:  2020_08_04_131052_remove_role_name_field (0.27 seconds)
Migrating: 2020_09_19_094251_add_activity_indexes
Migrated:  2020_09_19_094251_add_activity_indexes (0.63 seconds)
Migrating: 2020_09_27_210059_add_entity_soft_deletes
Migrated:  2020_09_27_210059_add_entity_soft_deletes (0.22 seconds)
Migrating: 2020_09_27_210528_create_deletions_table
Migrated:  2020_09_27_210528_create_deletions_table (1.04 seconds)
Migrating: 2020_11_07_232321_simplify_activities_table
Migrated:  2020_11_07_232321_simplify_activities_table (0.95 seconds)
Migrating: 2020_12_30_173528_add_owned_by_field_to_entities
Migrated:  2020_12_30_173528_add_owned_by_field_to_entities (1.12 seconds)
Migrating: 2021_01_30_225441_add_settings_type_column
Migrated:  2021_01_30_225441_add_settings_type_column (0.05 seconds)
Migrating: 2021_03_08_215138_add_user_slug
Migrated:  2021_03_08_215138_add_user_slug (0.28 seconds)

**Comment by Roxedus** [comment]
Please follow the issue template.
