### ISSUE TITLE
Change naming of docker tags

### ISSUE THREAD

**Issue by thetillhoff** [linuxserver/docker-bookstack#97]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

The version-tags on [`hub.docker.com`](https://hub.docker.com/r/linuxserver/bookstack/tags?page=1&ordering=last_updated) should have a simpler name. For example `v21.05`.

## Current Behavior

The current tag-naming seems to be `version-v21-05` which feels redundant.

**Comment by Roxedus** [comment]
This tagging is done across all our images, based out of templates. We cannot guarantee that the upstream app has a version prefixed with IE a V.
